In [2]:
import numpy as np
import pandas as pd

In [9]:
dataset = pd.read_csv("data/dataset.csv")
dataset.head(1)

,id,name,host_id,host_name,neighbourhood_group,neighbourhood,latitude,longitude,room_type,price,...,last_review,reviews_per_month,calculated_host_listings_count,availability_365,number_of_reviews_ltm,license,rating,bedrooms,beds,baths
0,1312228,Rental unit in Brooklyn · ★5.0 · 1 bedroom,7130382,Walter,Brooklyn,Clinton Hill,40.68371,-73.96461,Private room,55.0,...,2015-12-20,0.03,1,0,0,No License,5.0,1,1,Not specified

In [11]:
districts = dataset["neighbourhood_group"].unique()
small_districts = dataset["neighbourhood"].unique()
print(len(districts))
print(len(small_districts))
print(districts)
print(small_districts)

5
221
['Brooklyn' 'Manhattan' 'Queens' 'Bronx' 'Staten Island']
['Clinton Hill' "Hell's Kitchen" 'Chelsea' 'Washington Heights'
 'Murray Hill' 'Williamsburg' 'Sunset Park' 'Astoria' 'Financial District'
 'Sunnyside' 'Midtown' 'East Elmhurst' 'Upper West Side' 'West Village'
 'Kensington' 'Bushwick' 'Red Hook' 'Tribeca' 'Woodside'
 'Roosevelt Island' 'Concourse Village' 'Harlem' 'Flatbush'
 'University Heights' 'Flushing' 'Greenpoint' 'Ridgewood' 'Cypress Hills'
 "Prince's Bay" 'Port Richmond' 'East Village' 'Clason Point'
 'Bedford-Stuyvesant' 'Gravesend' 'Long Island City' 'Gramercy'
 'East Flatbush' 'East Harlem' 'St. George' 'Boerum Hill'
 'South Ozone Park' 'Park Slope' 'Crown Heights' 'Wakefield'
 'Forest Hills' 'Springfield Gardens' 'North Riverdale' 'Belmont' 'Corona'
 'Tremont' 'Elmhurst' 'Queens Village' 'Prospect-Lefferts Gardens'
 'Fort Greene' 'Allerton' 'Upper East Side' 'Richmond Hill' 'Kips Bay'
 'Morningside Heights' 'Flatlands' 'St. Albans' 'Bay Ridge' 'SoHo'
 'Lower East Side' 'West Brighton' 'Parkchester' 'Brownsville'
 'Ozone Park' 'Jackson Heights' 'Kew Gardens' 'Prospect Heights' 'Jamaica'
 'Arrochar' 'Kew Gardens Hills' 'Laurelton' 'Morris Park' 'Rosedale'
 'Arverne' 'Woodhaven' 'Norwood' 'Rosebank' 'Tompkinsville'
 'East New York' 'Far Rockaway' 'Edenwald' 'Baychester' 'Canarsie'
 'Williamsbridge' 'Kingsbridge' 'Rego Park' 'Sheepshead Bay'
 'Ditmars Steinway' 'Melrose' 'DUMBO' 'Theater District' 'Civic Center'
 'Chinatown' 'Flatiron District' 'Nolita' 'Bath Beach' 'East Morrisania'
 'Little Italy' 'Fresh Meadows' 'Midwood' 'Glendale' 'West Farms'
 'Carroll Gardens' 'Mount Hope' 'Gowanus' 'Windsor Terrace'
 'Downtown Brooklyn' 'Maspeth' 'South Slope' "Bull's Head" 'Navy Yard'
 'Stuyvesant Town' 'Borough Park' 'Dyker Heights' 'Greenwich Village'
 'College Point' 'Rockaway Beach' 'Mott Haven' 'Oakwood' 'Morris Heights'
 'Inwood' 'Cobble Hill' 'Jamaica Estates' 'Brighton Beach'
 'Brooklyn Heights' 'Vinegar Hill' 'Hollis' 'Jamaica Hills' 'Coney Island'
 'Arden Heights' 'New Springville' 'Bensonhurst' 'Howard Beach'
 'Throgs Neck' 'Cambria Heights' 'Battery Park City' 'Bayside' 'Briarwood'
 'Longwood' 'Shore Acres' 'Fordham' 'Whitestone' 'Unionport' 'Castle Hill'
 'Bergen Beach' 'Bayswater' 'Port Morris' 'Middle Village' 'NoHo'
 'Bellerose' 'Mount Eden' 'Emerson Hill' 'Pelham Bay' 'Randall Manor'
 'Mill Basin' 'Fort Hamilton' 'Eltingville' 'Woodrow' 'Clifton'
 'New Dorp Beach' 'Grant City' 'Edgemere' 'Lighthouse Hill' 'South Beach'
 'Rossville' 'Belle Harbor' 'New Brighton' 'Van Nest' 'Hunts Point'
 'Westchester Square' 'Spuyten Duyvil' 'Mariners Harbor' 'Midland Beach'
 'Concourse' 'Tottenville' 'Schuylerville' 'Marble Hill' 'Co-op City'
 'Stapleton' 'Morrisania' 'Claremont Village' 'Two Bridges' 'Concord'
 'Holliswood' 'Dongan Hills' 'City Island' 'Eastchester' 'Columbia St'
 'Bronxdale' 'Douglaston' 'Pelham Gardens' 'Olinville' 'Fieldston'
 'Highbridge' 'Richmondtown' 'Woodlawn' 'Bay Terrace' 'Huguenot'
 'Manhattan Beach' 'Silver Lake' 'Castleton Corners' 'Howland Hook'
 'Gerritsen Beach' 'Graniteville' 'Riverdale' 'Great Kills' 'Sea Gate'
 'Grymes Hill' 'Soundview' 'Breezy Point' 'Westerleigh'
 'Bay Terrace, Staten Island' 'Little Neck' 'Todt Hill' 'Neponsit'
 'Willowbrook' 'Chelsea, Staten Island']